// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartPS.Data;

#nullable disable

namespace SmartPS.Migrations
{
    [DbContext(typeof(SmartPsDbContext))]
    partial class SmartPsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartPS.Models.Audit.AuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("EntityId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PrevHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("AuditLogId");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("IX_AuditLogs_OccurredAtUtc");

                    b.HasIndex("PrevHash")
                        .IsUnique()
                        .HasDatabaseName("IX_AuditLogs_PrevHash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AuditLogs_UserId");

                    b.HasIndex("Username")
                        .HasDatabaseName("IX_AuditLogs_Username");

                    b.HasIndex("Action", "OccurredAtUtc")
                        .HasDatabaseName("IX_AuditLogs_Action_OccurredAtUtc");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditLogs_EntityType_EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("SmartPS.Models.Auth.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("PermissionId");

                    b.HasIndex("PermissionName")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("SmartPS.Models.Auth.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("SmartPS.Models.Auth.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("SmartPS.Models.Auth.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SmartPS.Models.Parking.BlacklistEntry", b =>
                {
                    b.Property<int>("BlacklistEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BlacklistEntryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RemoveReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RemovedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("BlacklistEntryId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("RemovedByUserId");

                    b.HasIndex(new[] { "LicensePlate" }, "IX_BlacklistEntries_LicensePlate");

                    b.HasIndex(new[] { "LicensePlate" }, "IX_BlacklistEntries_LicensePlate_Active")
                        .IsUnique()
                        .HasFilter("\"IsActive\"");

                    b.ToTable("BlacklistEntries", (string)null);
                });

            modelBuilder.Entity("SmartPS.Models.Parking.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("ApartmentCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Building")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultLicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IdentityCard")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsResident")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("VehicleTypeId")
                        .HasColumnType("integer");

                    b.HasKey("CustomerId");

                    b.HasIndex("ApartmentCode");

                    b.HasIndex("PhoneNumber");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("SmartPS.Models.Parking.CustomerTier", b =>
                {
                    b.Property<int>("TierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TierId"));

                    b.Property<string>("BadgeColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("#64748B");

                    b.Property<string>("BadgeIcon")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("👤");

                    b.Property<int>("CustomerType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<double>("DiscountPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TierId");

                    b.HasIndex("CustomerType")
                        .IsUnique();

                    b.ToTable("CustomerTiers", (string)null);
                });

            modelBuilder.Entity("SmartPS.Models.Parking.CustomerVehicle", b =>
                {
                    b.Property<int>("CustomerVehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerVehicleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("integer");

                    b.HasKey("CustomerVehicleId");

                    b.HasIndex("VehicleTypeId");

                    b.HasIndex(new[] { "CustomerId" }, "IX_CustomerVehicles_CustomerId");

                    b.HasIndex(new[] { "LicensePlate" }, "IX_CustomerVehicles_LicensePlate_Active")
                        .IsUnique()
                        .HasFilter("\"IsActive\"");

                    b.ToTable("CustomerVehicles", (string)null);
                });

            modelBuilder.Entity("SmartPS.Models.Parking.MonthlyTicket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TicketId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MonthlyPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("PlanId")
                        .HasColumnType("integer");

                    b.Property<string>("RegisteredLicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("integer");

                    b.HasKey("TicketId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PlanId");

                    b.HasIndex("RegisteredLicensePlate");

                    b.HasIndex("TicketCode")
                        .IsUnique();

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("MonthlyTickets", (string)null);
                });

            modelBuilder.Entity("SmartPS.Models.Parking.MonthlyTicketPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<double>("DiscountPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<int>("DurationMonths")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PricePerMonth")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("integer");

                    b.HasKey("PlanId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("MonthlyTicketPlans", (string)null);
                });

            modelBuilder.Entity("SmartPS.Models.Parking.MonthlyTicketPurchase", b =>
                {
                    b.Property<long>("MonthlyTicketPurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MonthlyTicketPurchaseId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PeriodEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PlanId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.HasKey("MonthlyTicketPurchaseId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PlanId");

                    b.HasIndex("TicketId");

                    b.HasIndex(new[] { "CreatedAtUtc" }, "IX_MonthlyTicketPurchases_CreatedAtUtc");

                    b.ToTable("MonthlyTicketPurchases", (string)null);
                });

            modelBuilder.Entity("SmartPS.Models.Parking.ParkingSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SessionId"));

                    b.Property<string>("CheckInImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CheckOutImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsMonthlyPass")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PaymentMethod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("SlotId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TotalFee")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0.0m);

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("integer");

                    b.HasKey("SessionId");

                    b.HasIndex("CheckInTime");

                    b.HasIndex("CheckOutTime");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LicensePlate");

                    b.HasIndex("Status");

                    b.HasIndex("TicketCode");

                    b.HasIndex("VehicleTypeId");

                    b.HasIndex(new[] { "SlotId" }, "IX_ParkingSessions_SlotId");

                    b.HasIndex(new[] { "SlotId" }, "IX_ParkingSessions_SlotId_Active")
                        .IsUnique()
                        .HasFilter("\"Status\" = 0 AND \"SlotId\" IS NOT NULL");

                    b.ToTable("ParkingSessions", (string)null);
                });

            modelBuilder.Entity("SmartPS.Models.Parking.ParkingSlot", b =>
                {
                    b.Property<int>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SlotId"));

                    b.Property<double>("CoordX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<double>("CoordY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("CurrentLicensePlate")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<double>("Height")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(120.0);

                    b.Property<string>("SlotCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("integer");

                    b.Property<double>("Width")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(80.0);

                    b.Property<int?>("ZoneId")
                        .HasColumnType("integer");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("SlotId");

                    b.HasIndex("SlotCode")
                        .IsUnique();

                    b.HasIndex("VehicleTypeId");

                    b.HasIndex("ZoneId");

                    b.ToTable("ParkingSlots", (string)null);
                });

            modelBuilder.Entity("SmartPS.Models.Parking.ParkingZone", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ZoneId"));

                    b.Property<int>("Audience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TotalCapacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("VehicleTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("ZoneCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ZoneId");

                    b.HasIndex("VehicleTypeId");

                    b.HasIndex("ZoneCode")
                        .IsUnique();

                    b.ToTable("ParkingZones", (string)null);
                });

            modelBuilder.Entity("SmartPS.Models.Parking.PricingRule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RuleId"));

                    b.Property<decimal>("AdditionalPricePerHour")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("FirstBlockMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(120);

                    b.Property<decimal>("FirstBlockPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("OvernightPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("integer");

                    b.HasKey("RuleId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("PricingRules", (string)null);
                });

            modelBuilder.Entity("SmartPS.Models.Parking.VehicleType", b =>
                {
                    b.Property<int>("VehicleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehicleTypeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("VehicleTypeId");

                    b.HasIndex("TypeName")
                        .IsUnique();

                    b.ToTable("VehicleTypes", (string)null);
                });

            modelBuilder.Entity("SmartPS.Models.Payment.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CheckoutImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("CheckoutUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PaymentId");

                    b.HasIndex("CheckoutUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("IX_Payments_SessionId_Active")
                        .HasFilter("\"Status\" IN (0, 1)");

                    b.HasIndex("ShiftId");

                    b.HasIndex("Status");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("SmartPS.Models.Payment.PaymentAttempt", b =>
                {
                    b.Property<int>("PaymentAttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentAttemptId"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PaymentTransactionId")
                        .HasColumnType("integer");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("text");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("PaymentAttemptId");

                    b.HasIndex("PaymentTransactionId");

                    b.ToTable("PaymentAttempts", (string)null);
                });

            modelBuilder.Entity("SmartPS.Models.Payment.PaymentTransaction", b =>
                {
                    b.Property<int>("PaymentTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentTransactionId"));

                    b.Property<string>("AccountName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BankCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CheckoutUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("GatewayOrderCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("GatewayTransactionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("PaymentId")
                        .HasColumnType("integer");

                    b.Property<string>("QrCodePayload")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PaymentTransactionId");

                    b.HasIndex("GatewayOrderCode");

                    b.HasIndex("PaymentId");

                    b.HasIndex("TransactionReference")
                        .IsUnique();

                    b.ToTable("PaymentTransactions", (string)null);
                });

            modelBuilder.Entity("SmartPS.Models.Payment.PaymentWebhook", b =>
                {
                    b.Property<int>("PaymentWebhookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentWebhookId"));

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDuplicate")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PaymentTransactionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Signature")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("PaymentWebhookId");

                    b.HasIndex("PaymentTransactionId");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("TransactionReference");

                    b.HasIndex("Provider", "EventId")
                        .IsUnique();

                    b.ToTable("PaymentWebhooks", (string)null);
                });

            modelBuilder.Entity("SmartPS.Models.Shifts.FinancialTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("ParkingSessionId")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<string>("ReferenceCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("TransactionId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ParkingSessionId");

                    b.HasIndex("PaymentMethod");

                    b.HasIndex("ShiftId");

                    b.HasIndex("TransactionCode")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.HasIndex("ParkingSessionId", "Type")
                        .IsUnique()
                        .HasDatabaseName("IX_FinancialTransactions_OneParkingFeePerSession")
                        .HasFilter("\"ParkingSessionId\" IS NOT NULL AND \"Type\" = 0");

                    b.ToTable("FinancialTransactions", (string)null);
                });

            modelBuilder.Entity("SmartPS.Models.Shifts.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShiftId"));

                    b.Property<decimal?>("ActualCash")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("BeginningCash")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Difference")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("ExpectedCash")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ManagerNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OpenedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("ShiftId");

                    b.HasIndex("OpenedAt");

                    b.HasIndex("OpenedByUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Shifts_OneActivePerUser")
                        .HasFilter("\"Status\" = 0");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("OpenedByUserId", "Status");

                    b.ToTable("Shifts", (string)null);
                });

            modelBuilder.Entity("SmartPS.Models.Auth.RolePermission", b =>
                {
                    b.HasOne("SmartPS.Models.Auth.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartPS.Models.Auth.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SmartPS.Models.Auth.User", b =>
                {
                    b.HasOne("SmartPS.Models.Auth.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SmartPS.Models.Parking.BlacklistEntry", b =>
                {
                    b.HasOne("SmartPS.Models.Auth.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartPS.Models.Auth.User", "RemovedByUser")
                        .WithMany()
                        .HasForeignKey("RemovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("RemovedByUser");
                });

            modelBuilder.Entity("SmartPS.Models.Parking.Customer", b =>
                {
                    b.HasOne("SmartPS.Models.Parking.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("SmartPS.Models.Parking.CustomerVehicle", b =>
                {
                    b.HasOne("SmartPS.Models.Parking.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartPS.Models.Parking.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("SmartPS.Models.Parking.MonthlyTicket", b =>
                {
                    b.HasOne("SmartPS.Models.Parking.Customer", "Customer")
                        .WithMany("MonthlyTickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartPS.Models.Parking.MonthlyTicketPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartPS.Models.Parking.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Plan");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("SmartPS.Models.Parking.MonthlyTicketPlan", b =>
                {
                    b.HasOne("SmartPS.Models.Parking.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("SmartPS.Models.Parking.MonthlyTicketPurchase", b =>
                {
                    b.HasOne("SmartPS.Models.Auth.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartPS.Models.Parking.MonthlyTicketPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartPS.Models.Parking.MonthlyTicket", "Ticket")
                        .WithMany("Purchases")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Plan");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("SmartPS.Models.Parking.ParkingSession", b =>
                {
                    b.HasOne("SmartPS.Models.Auth.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartPS.Models.Parking.Customer", "Customer")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartPS.Models.Parking.ParkingSlot", "Slot")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartPS.Models.Parking.VehicleType", "VehicleType")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("Slot");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("SmartPS.Models.Parking.ParkingSlot", b =>
                {
                    b.HasOne("SmartPS.Models.Parking.VehicleType", "VehicleType")
                        .WithMany("ParkingSlots")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartPS.Models.Parking.ParkingZone", "Zone")
                        .WithMany("Slots")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("VehicleType");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("SmartPS.Models.Parking.ParkingZone", b =>
                {
                    b.HasOne("SmartPS.Models.Parking.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("SmartPS.Models.Parking.PricingRule", b =>
                {
                    b.HasOne("SmartPS.Models.Parking.VehicleType", "VehicleType")
                        .WithMany("PricingRules")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("SmartPS.Models.Payment.Payment", b =>
                {
                    b.HasOne("SmartPS.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("CheckoutUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartPS.Models.Parking.ParkingSession", "Session")
                        .WithMany("Payments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartPS.Models.Shifts.Shift", null)
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SmartPS.Models.Payment.PaymentAttempt", b =>
                {
                    b.HasOne("SmartPS.Models.Payment.PaymentTransaction", "PaymentTransaction")
                        .WithMany("Attempts")
                        .HasForeignKey("PaymentTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentTransaction");
                });

            modelBuilder.Entity("SmartPS.Models.Payment.PaymentTransaction", b =>
                {
                    b.HasOne("SmartPS.Models.Payment.Payment", "Payment")
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("SmartPS.Models.Payment.PaymentWebhook", b =>
                {
                    b.HasOne("SmartPS.Models.Payment.PaymentTransaction", "PaymentTransaction")
                        .WithMany("Webhooks")
                        .HasForeignKey("PaymentTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PaymentTransaction");
                });

            modelBuilder.Entity("SmartPS.Models.Shifts.FinancialTransaction", b =>
                {
                    b.HasOne("SmartPS.Models.Auth.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartPS.Models.Parking.ParkingSession", "ParkingSession")
                        .WithMany()
                        .HasForeignKey("ParkingSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartPS.Models.Shifts.Shift", "Shift")
                        .WithMany("Transactions")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ParkingSession");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("SmartPS.Models.Shifts.Shift", b =>
                {
                    b.HasOne("SmartPS.Models.Auth.User", "OpenedByUser")
                        .WithMany()
                        .HasForeignKey("OpenedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartPS.Models.Auth.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OpenedByUser");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("SmartPS.Models.Auth.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("SmartPS.Models.Auth.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmartPS.Models.Parking.Customer", b =>
                {
                    b.Navigation("MonthlyTickets");

                    b.Navigation("ParkingSessions");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("SmartPS.Models.Parking.MonthlyTicket", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("SmartPS.Models.Parking.ParkingSession", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SmartPS.Models.Parking.ParkingSlot", b =>
                {
                    b.Navigation("ParkingSessions");
                });

            modelBuilder.Entity("SmartPS.Models.Parking.ParkingZone", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("SmartPS.Models.Parking.VehicleType", b =>
                {
                    b.Navigation("ParkingSessions");

                    b.Navigation("ParkingSlots");

                    b.Navigation("PricingRules");
                });

            modelBuilder.Entity("SmartPS.Models.Payment.Payment", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SmartPS.Models.Payment.PaymentTransaction", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Webhooks");
                });

            modelBuilder.Entity("SmartPS.Models.Shifts.Shift", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
